// This file is auto-generated by @hey-api/openapi-ts

export const APIErrorSchema = {
    properties: {
        status_code: {
            type: 'integer',
            title: 'Status Code',
            default: 400
        },
        detail: {
            type: 'string',
            title: 'Detail',
            default: 'Something Wrong'
        }
    },
    type: 'object',
    title: 'APIError'
} as const;

export const Body_Auth_signinSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_Auth-signin'
} as const;

export const ForbiddenSchema = {
    properties: {
        status_code: {
            type: 'integer',
            title: 'Status Code',
            default: 400
        },
        detail: {
            type: 'string',
            title: 'Detail',
            default: 'Something Wrong'
        }
    },
    type: 'object',
    title: 'Forbidden'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        created_in: {
            type: 'string',
            format: 'date-time',
            title: 'Created In'
        },
        last_update: {
            type: 'string',
            format: 'date-time',
            title: 'Last Update'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        thread_id: {
            type: 'string',
            format: 'uuid',
            title: 'Thread Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'text',
        'created_in',
        'last_update',
        'user_id',
        'thread_id'
    ],
    title: 'Message'
} as const;

export const MessageCreateSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: [
        'text'
    ],
    title: 'MessageCreate'
} as const;

export const MessageUpdateSchema = {
    properties: {
        text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Text'
        }
    },
    type: 'object',
    title: 'MessageUpdate'
} as const;

export const NotFoundSchema = {
    properties: {
        status_code: {
            type: 'integer',
            title: 'Status Code',
            default: 400
        },
        detail: {
            type: 'string',
            title: 'Detail',
            default: 'Something Wrong'
        }
    },
    type: 'object',
    title: 'NotFound'
} as const;

export const ThreadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_in: {
            type: 'string',
            format: 'date-time',
            title: 'Created In'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_in',
        'owner_id'
    ],
    title: 'Thread'
} as const;

export const ThreadCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ThreadCreate'
} as const;

export const ThreadUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'ThreadUpdate'
} as const;

export const ThreadWithMessagesSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_in: {
            type: 'string',
            format: 'date-time',
            title: 'Created In'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        messages: {
            items: {
                $ref: '#/components/schemas/Message'
            },
            type: 'array',
            title: 'Messages'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_in',
        'owner_id',
        'messages'
    ],
    title: 'ThreadWithMessages'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        expired_in: {
            type: 'string',
            format: 'date-time',
            title: 'Expired In'
        }
    },
    type: 'object',
    required: [
        'access_token',
        'user_id',
        'expired_in'
    ],
    title: 'Token'
} as const;

export const UserSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        mail: {
            type: 'string',
            format: 'email',
            title: 'Mail'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'mail'
    ],
    title: 'User'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
