// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import { authSessionResponseTransformer, authSigninResponseTransformer, messageCreateMessageResponseTransformer, messageCreateThreadResponseTransformer, messageDeleteMessageResponseTransformer, messageDeleteThreadResponseTransformer, messageGetThreadResponseTransformer, messageGetThreadsResponseTransformer, messageUpdateMessageResponseTransformer, messageUpdateThreadResponseTransformer } from './transformers.gen';
import type { AuthCallbackData, AuthCallbackErrors, AuthCallbackResponses, AuthSessionData, AuthSessionErrors, AuthSessionResponses, AuthSigninData, AuthSigninErrors, AuthSigninResponses, AuthSignoutData, AuthSignoutErrors, AuthSignoutResponses, AuthSignupData, AuthSignupErrors, AuthSignupHtmlData, AuthSignupHtmlErrors, AuthSignupHtmlResponses, AuthSignupResponses, MessageCreateMessageData, MessageCreateMessageErrors, MessageCreateMessageResponses, MessageCreateThreadData, MessageCreateThreadErrors, MessageCreateThreadResponses, MessageDeleteMessageData, MessageDeleteMessageErrors, MessageDeleteMessageResponses, MessageDeleteThreadData, MessageDeleteThreadErrors, MessageDeleteThreadResponses, MessageGetThreadData, MessageGetThreadErrors, MessageGetThreadResponses, MessageGetThreadsData, MessageGetThreadsErrors, MessageGetThreadsResponses, MessageUpdateMessageData, MessageUpdateMessageErrors, MessageUpdateMessageResponses, MessageUpdateThreadData, MessageUpdateThreadErrors, MessageUpdateThreadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AuthService {
    /**
     * Signin
     */
    public static authSignin<ThrowOnError extends boolean = false>(options: Options<AuthSigninData, ThrowOnError>) {
        return (options.client ?? client).post<AuthSigninResponses, AuthSigninErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseTransformer: authSigninResponseTransformer,
            url: '/auth/signin',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Signup Html
     */
    public static authSignupHtml<ThrowOnError extends boolean = false>(options?: Options<AuthSignupHtmlData, ThrowOnError>) {
        return (options?.client ?? client).get<AuthSignupHtmlResponses, AuthSignupHtmlErrors, ThrowOnError>({ url: '/auth/signup', ...options });
    }
    
    /**
     * Signup
     */
    public static authSignup<ThrowOnError extends boolean = false>(options?: Options<AuthSignupData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthSignupResponses, AuthSignupErrors, ThrowOnError>({
            url: '/auth/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Signout
     */
    public static authSignout<ThrowOnError extends boolean = false>(options?: Options<AuthSignoutData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthSignoutResponses, AuthSignoutErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/signout',
            ...options
        });
    }
    
    /**
     * Session
     */
    public static authSession<ThrowOnError extends boolean = false>(options?: Options<AuthSessionData, ThrowOnError>) {
        return (options?.client ?? client).get<AuthSessionResponses, AuthSessionErrors, ThrowOnError>({
            responseTransformer: authSessionResponseTransformer,
            url: '/auth/session',
            ...options
        });
    }
    
    /**
     * Callback
     */
    public static authCallback<ThrowOnError extends boolean = false>(options?: Options<AuthCallbackData, ThrowOnError>) {
        return (options?.client ?? client).get<AuthCallbackResponses, AuthCallbackErrors, ThrowOnError>({ url: '/auth/callback', ...options });
    }
}

export class MessageService {
    /**
     * Get Threads
     */
    public static messageGetThreads<ThrowOnError extends boolean = false>(options?: Options<MessageGetThreadsData, ThrowOnError>) {
        return (options?.client ?? client).get<MessageGetThreadsResponses, MessageGetThreadsErrors, ThrowOnError>({
            responseTransformer: messageGetThreadsResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/',
            ...options
        });
    }
    
    /**
     * Create Thread
     */
    public static messageCreateThread<ThrowOnError extends boolean = false>(options: Options<MessageCreateThreadData, ThrowOnError>) {
        return (options.client ?? client).post<MessageCreateThreadResponses, MessageCreateThreadErrors, ThrowOnError>({
            responseTransformer: messageCreateThreadResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Thread
     */
    public static messageDeleteThread<ThrowOnError extends boolean = false>(options: Options<MessageDeleteThreadData, ThrowOnError>) {
        return (options.client ?? client).delete<MessageDeleteThreadResponses, MessageDeleteThreadErrors, ThrowOnError>({
            responseTransformer: messageDeleteThreadResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/{thread_id}/',
            ...options
        });
    }
    
    /**
     * Get Thread
     */
    public static messageGetThread<ThrowOnError extends boolean = false>(options: Options<MessageGetThreadData, ThrowOnError>) {
        return (options.client ?? client).get<MessageGetThreadResponses, MessageGetThreadErrors, ThrowOnError>({
            responseTransformer: messageGetThreadResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/{thread_id}/',
            ...options
        });
    }
    
    /**
     * Create Message
     */
    public static messageCreateMessage<ThrowOnError extends boolean = false>(options: Options<MessageCreateMessageData, ThrowOnError>) {
        return (options.client ?? client).post<MessageCreateMessageResponses, MessageCreateMessageErrors, ThrowOnError>({
            responseTransformer: messageCreateMessageResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/{thread_id}/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update Thread
     */
    public static messageUpdateThread<ThrowOnError extends boolean = false>(options: Options<MessageUpdateThreadData, ThrowOnError>) {
        return (options.client ?? client).put<MessageUpdateThreadResponses, MessageUpdateThreadErrors, ThrowOnError>({
            responseTransformer: messageUpdateThreadResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/{thread_id}/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Message
     */
    public static messageDeleteMessage<ThrowOnError extends boolean = false>(options: Options<MessageDeleteMessageData, ThrowOnError>) {
        return (options.client ?? client).delete<MessageDeleteMessageResponses, MessageDeleteMessageErrors, ThrowOnError>({
            responseTransformer: messageDeleteMessageResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/{thread_id}/{message_id}/',
            ...options
        });
    }
    
    /**
     * Update Message
     */
    public static messageUpdateMessage<ThrowOnError extends boolean = false>(options: Options<MessageUpdateMessageData, ThrowOnError>) {
        return (options.client ?? client).put<MessageUpdateMessageResponses, MessageUpdateMessageErrors, ThrowOnError>({
            responseTransformer: messageUpdateMessageResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/message/{thread_id}/{message_id}/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
