// This file is auto-generated by @hey-api/openapi-ts

import type { AuthSessionResponse, AuthSigninResponse, MessageCreateMessageResponse, MessageCreateThreadResponse, MessageDeleteMessageResponse, MessageDeleteThreadResponse, MessageGetThreadResponse, MessageGetThreadsResponse, MessageUpdateMessageResponse, MessageUpdateThreadResponse } from './types.gen';

const tokenSchemaResponseTransformer = (data: any) => {
    data.expired_in = new Date(data.expired_in);
    return data;
};

export const authSigninResponseTransformer = async (data: any): Promise<AuthSigninResponse> => {
    data = tokenSchemaResponseTransformer(data);
    return data;
};

export const authSessionResponseTransformer = async (data: any): Promise<AuthSessionResponse> => {
    data = data.map((item: any) => tokenSchemaResponseTransformer(item));
    return data;
};

const threadSchemaResponseTransformer = (data: any) => {
    data.created_in = new Date(data.created_in);
    return data;
};

export const messageGetThreadsResponseTransformer = async (data: any): Promise<MessageGetThreadsResponse> => {
    data = data.map((item: any) => threadSchemaResponseTransformer(item));
    return data;
};

export const messageCreateThreadResponseTransformer = async (data: any): Promise<MessageCreateThreadResponse> => {
    data = threadSchemaResponseTransformer(data);
    return data;
};

export const messageDeleteThreadResponseTransformer = async (data: any): Promise<MessageDeleteThreadResponse> => {
    data = threadSchemaResponseTransformer(data);
    return data;
};

const threadWithMessagesSchemaResponseTransformer = (data: any) => {
    data.created_in = new Date(data.created_in);
    data.messages = data.messages.map((item: any) => messageSchemaResponseTransformer(item));
    return data;
};

const messageSchemaResponseTransformer = (data: any) => {
    data.created_in = new Date(data.created_in);
    data.last_update = new Date(data.last_update);
    return data;
};

export const messageGetThreadResponseTransformer = async (data: any): Promise<MessageGetThreadResponse> => {
    data = threadWithMessagesSchemaResponseTransformer(data);
    return data;
};

export const messageCreateMessageResponseTransformer = async (data: any): Promise<MessageCreateMessageResponse> => {
    data = messageSchemaResponseTransformer(data);
    return data;
};

export const messageUpdateThreadResponseTransformer = async (data: any): Promise<MessageUpdateThreadResponse> => {
    data = threadSchemaResponseTransformer(data);
    return data;
};

export const messageDeleteMessageResponseTransformer = async (data: any): Promise<MessageDeleteMessageResponse> => {
    data = messageSchemaResponseTransformer(data);
    return data;
};

export const messageUpdateMessageResponseTransformer = async (data: any): Promise<MessageUpdateMessageResponse> => {
    data = messageSchemaResponseTransformer(data);
    return data;
};
