// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

/**
 * APIError
 */
export type ApiError = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Detail
     */
    detail?: string;
};

/**
 * Body_Auth-signin
 */
export type BodyAuthSignin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Forbidden
 */
export type Forbidden = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Detail
     */
    detail?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Id
     */
    id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Created In
     */
    created_in: Date;
    /**
     * Last Update
     */
    last_update: Date;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Thread Id
     */
    thread_id: string;
};

/**
 * MessageCreate
 */
export type MessageCreate = {
    /**
     * Text
     */
    text: string;
};

/**
 * MessageUpdate
 */
export type MessageUpdate = {
    /**
     * Text
     */
    text?: string | null;
};

/**
 * NotFound
 */
export type NotFound = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Detail
     */
    detail?: string;
};

/**
 * Thread
 */
export type Thread = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created In
     */
    created_in: Date;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * ThreadCreate
 */
export type ThreadCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ThreadUpdate
 */
export type ThreadUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ThreadWithMessages
 */
export type ThreadWithMessages = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created In
     */
    created_in: Date;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Messages
     */
    messages: Array<Message>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Expired In
     */
    expired_in: Date;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Mail
     */
    mail: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AuthSigninData = {
    body: BodyAuthSignin;
    path?: never;
    query?: {
        /**
         * Return Url
         */
        return_url?: string;
    };
    url: '/auth/signin';
};

export type AuthSigninErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthSigninError = AuthSigninErrors[keyof AuthSigninErrors];

export type AuthSigninResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthSigninResponse = AuthSigninResponses[keyof AuthSigninResponses];

export type AuthSignupHtmlData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return Url
         */
        return_url?: string;
    };
    url: '/auth/signup';
};

export type AuthSignupHtmlErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthSignupHtmlError = AuthSignupHtmlErrors[keyof AuthSignupHtmlErrors];

export type AuthSignupHtmlResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type AuthSignupHtmlResponse = AuthSignupHtmlResponses[keyof AuthSignupHtmlResponses];

export type AuthSignupData = {
    /**
     * UserCreate
     */
    body?: {
        /**
         * Name
         */
        name: string;
        /**
         * Mail
         */
        mail: string;
        /**
         * Password
         */
        password: string;
    };
    path?: never;
    query?: {
        /**
         * Return Url
         */
        return_url?: string;
    };
    url: '/auth/signup';
};

export type AuthSignupErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];

export type AuthSignoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/signout';
};

export type AuthSignoutErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
};

export type AuthSignoutError = AuthSignoutErrors[keyof AuthSignoutErrors];

export type AuthSignoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type AuthSessionErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
};

export type AuthSessionError = AuthSessionErrors[keyof AuthSessionErrors];

export type AuthSessionResponses = {
    /**
     * Response Auth-Session
     *
     * Successful Response
     */
    200: Array<Token>;
};

export type AuthSessionResponse = AuthSessionResponses[keyof AuthSessionResponses];

export type AuthCallbackData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Mail Token
         */
        mail_token?: string | null;
    };
    url: '/auth/callback';
};

export type AuthCallbackErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthCallbackError = AuthCallbackErrors[keyof AuthCallbackErrors];

export type AuthCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MessageGetThreadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/message/';
};

export type MessageGetThreadsErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
};

export type MessageGetThreadsError = MessageGetThreadsErrors[keyof MessageGetThreadsErrors];

export type MessageGetThreadsResponses = {
    /**
     * Response Message-Get Threads
     *
     * Successful Response
     */
    200: Array<Thread>;
};

export type MessageGetThreadsResponse = MessageGetThreadsResponses[keyof MessageGetThreadsResponses];

export type MessageCreateThreadData = {
    body: ThreadCreate;
    path?: never;
    query?: never;
    url: '/message/';
};

export type MessageCreateThreadErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageCreateThreadError = MessageCreateThreadErrors[keyof MessageCreateThreadErrors];

export type MessageCreateThreadResponses = {
    /**
     * Successful Response
     */
    200: Thread;
};

export type MessageCreateThreadResponse = MessageCreateThreadResponses[keyof MessageCreateThreadResponses];

export type MessageDeleteThreadData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/message/{thread_id}/';
};

export type MessageDeleteThreadErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageDeleteThreadError = MessageDeleteThreadErrors[keyof MessageDeleteThreadErrors];

export type MessageDeleteThreadResponses = {
    /**
     * Successful Response
     */
    200: Thread;
};

export type MessageDeleteThreadResponse = MessageDeleteThreadResponses[keyof MessageDeleteThreadResponses];

export type MessageGetThreadData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/message/{thread_id}/';
};

export type MessageGetThreadErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageGetThreadError = MessageGetThreadErrors[keyof MessageGetThreadErrors];

export type MessageGetThreadResponses = {
    /**
     * Successful Response
     */
    200: ThreadWithMessages;
};

export type MessageGetThreadResponse = MessageGetThreadResponses[keyof MessageGetThreadResponses];

export type MessageCreateMessageData = {
    body: MessageCreate;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/message/{thread_id}/';
};

export type MessageCreateMessageErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageCreateMessageError = MessageCreateMessageErrors[keyof MessageCreateMessageErrors];

export type MessageCreateMessageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type MessageCreateMessageResponse = MessageCreateMessageResponses[keyof MessageCreateMessageResponses];

export type MessageUpdateThreadData = {
    body: ThreadUpdate;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/message/{thread_id}/';
};

export type MessageUpdateThreadErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageUpdateThreadError = MessageUpdateThreadErrors[keyof MessageUpdateThreadErrors];

export type MessageUpdateThreadResponses = {
    /**
     * Successful Response
     */
    200: Thread;
};

export type MessageUpdateThreadResponse = MessageUpdateThreadResponses[keyof MessageUpdateThreadResponses];

export type MessageDeleteMessageData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/message/{thread_id}/{message_id}/';
};

export type MessageDeleteMessageErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageDeleteMessageError = MessageDeleteMessageErrors[keyof MessageDeleteMessageErrors];

export type MessageDeleteMessageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type MessageDeleteMessageResponse = MessageDeleteMessageResponses[keyof MessageDeleteMessageResponses];

export type MessageUpdateMessageData = {
    body: MessageUpdate;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/message/{thread_id}/{message_id}/';
};

export type MessageUpdateMessageErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: Forbidden;
    /**
     * Not Found
     */
    404: NotFound;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageUpdateMessageError = MessageUpdateMessageErrors[keyof MessageUpdateMessageErrors];

export type MessageUpdateMessageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type MessageUpdateMessageResponse = MessageUpdateMessageResponses[keyof MessageUpdateMessageResponses];
